spring:
  application:
    name: gateway-service
server:
  port: 9020
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka}
  instance:
    preferIpAddress: true
