spring:
  application:
    name: feed-service
server:
  port: ${PORT:9010}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka}
  instance:
    preferIpAddress: true
