spring:
  application:
    name: feed-service
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
