spring:
  application:
    name: eureka-server

server:
  port: ${PORT}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME}
